### ISSUE TITLE
Question about SP publib/private key requirement for SHA-256 usage

### ISSUE THREAD

**Issue by ymartin59** [choonchernlim/spring-security-adfs-saml2#8]
Hello

First many thanks for publishing all these details about ADFS setup with SHA-256 signature support...because I really failed to get it work with SHA-1, probably I made a mistake somewhere in the sequence.

I have first generated my SP private key according to http://docs.spring.io/autorepo/docs/spring-security-saml/current/reference/htmlsingle/#configuration-key-management-private-keys

but when enabling metadata signature option to SHA-256, metadata generation then fails with

```
Caused by: org.apache.xml.security.signature.XMLSignatureException: No installed provider supports this key: sun.security.provider.DSAPrivateKey
                at org.apache.xml.security.algorithms.implementations.SignatureBaseRSA.engineInitSign(SignatureBaseRSA.java:167) ~[xmlsec-1.5.6.jar:1.5.6]
                at org.apache.xml.security.algorithms.SignatureAlgorithm.initSign(SignatureAlgorithm.java:238) ~[xmlsec-1.5.6.jar:1.5.6]
                at org.apache.xml.security.signature.XMLSignature.sign(XMLSignature.java:592) ~[xmlsec-1.5.6.jar:1.5.6]
                at org.opensaml.xml.signature.Signer.signObject(Signer.java:77) ~[xmltooling-1.4.1.jar:?]
                ... 70 more
Caused by: java.security.InvalidKeyException: No installed provider supports this key: sun.security.provider.DSAPrivateKey
                at java.security.Signature$Delegate.chooseProvider(Signature.java:1135) ~[?:1.8.0_111]
                at java.security.Signature$Delegate.engineInitSign(Signature.java:1176) ~[?:1.8.0_111]
                at java.security.Signature.initSign(Signature.java:527) ~[?:1.8.0_111]
                at org.apache.xml.security.algorithms.implementations.SignatureBaseRSA.engineInitSign(SignatureBaseRSA.java:165) ~[xmlsec-1.5.6.jar:1.5.6]
                at org.apache.xml.security.algorithms.SignatureAlgorithm.initSign(SignatureAlgorithm.java:238) ~[xmlsec-1.5.6.jar:1.5.6]
                at org.apache.xml.security.signature.XMLSignature.sign(XMLSignature.java:592) ~[xmlsec-1.5.6.jar:1.5.6]
                at org.opensaml.xml.signature.Signer.signObject(Signer.java:77) ~[xmltooling-1.4.1.jar:?]
                ... 70 more
```

So I guessed that my private key was not consistent with signature requirements and I generated a new one with additional keytool options `-keyalg RSA -keysize 2048 -sigalg SHA256withRSA`

May you please confirm that was the right thing to do, and maybe you generate your private key the same way ? If so please - please - add this important information in your `README.md`.

Again thanks for your blog entries and this setup sample project.
Regards
Yves

**Comment by choonchernlim** [comment]
By looking at the error, it appears you might be mixing DSA with RSA key. 

What you did latter was the correct approach. I did the same thing on my end. 

I have updated `README.md` to make this part clearer. Thank you.
